spring:
  application:
    name: Just for me

  data:
    mongodb:
      uri: mongodb+srv://au7_anmol_upadhyay:fWTdybUrJNvrCv0S@cluster0.g0m4djj.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

    redis:
      url: redis://default:VVcicIx6vpTwxe81YAZTfCTY1OwYCQiL@redis-19143.crce217.ap-south-1-1.ec2.cloud.redislabs.com:19143

  mail:
    host: smtp.gmail.com
    port: 587
    username: anmolupadhyayau7au7@gmail.com
    password: "mmvy mldg eguv danm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

weather:
  api:
    key: 0c9d97a1242719cef78916cc667c1e23

quotes:
  api:
    key: +n0AqD3hLN0Ig9Jh/XuMHw==95hOn31kp7cr0MI5
#
#logging:
#  level:
#    net:
#      au7:
#        journalApp : TRACE
